### PR TITLE
NEW make sell or eat by mandatory in product lot (PR #21710)

### PR DESCRIPTION
**Pull request by lvessiller-opendsi**
NEW make sell or eat by mandatory in product lot (see PR #21709 for SQL install)

- Add a "make sell-by or eat-by date" mandatory in a product card when product batch is enabled
image

If sell-by or eat-by is mandatory then, we have these fields required when we create or update or product batch :
1) On create
image

2) On update
image

3) And an error message is shown if one of these fields are empty
image

4) We also check these mandatory fields on stock correction
image

5) And check on dispatch from supplier order
image

6) And when reception is enabled we also have this check
image

### CODE REVIEW

**Comment by lvessiller-opendsi** [comment]
@eldy
Have you any suggestion ?
Could you merge it ?

**Comment by lvessiller-opendsi** [comment]
**Attention** : la fonction  editfieldval() a été modifiée dans Dolibarr v18 (develop) et un paramètre a été ajouté
Il faudra reprendre dans le fichier "product_card.php" aux lignes 510 et 520 pour avoir les derniers paramètres lors de l'appel à la fonction "editfieldval()"

**Comment by kkhelifa-opendsi** [comment]
Lier à https://github.com/Easya-Solutions/dolibarr/pull/255 (si elle est mergé, merger celle-ci)

**Comment by kkhelifa-opendsi** [comment]
PR #24911

**Pull request merged**
